### PR TITLE
❇️ migration from request library to axios

### PR DESCRIPTION
**Pull request by Archish27**

### CODE REVIEW

**Comment by xcafebabe** [comment]
Hi @Archish27 ! I'm glad you're making this change!, Is there a way we can build the cli with your branch version  to test it in our pipelines, in that way we can also help as beta testers.

**Comment by Archish27** [comment]
@xcafebabe Yes, it's working branch. Just it doesn't have newer features which were released in cypress cli. Still you can use this branch to trigger tests on BrowserStack.

**Comment by xcafebabe** [comment]
> @xcafebabe Yes, it's working branch. Just it doesn't have newer features which were released in cypress cli. Still you can use this branch to trigger tests on BrowserStack.

ok cool! i'm going to use this branch in our pipelines 👍🏼

**Comment by xcafebabe** [comment]
so far so good 👍🏼

**Comment by pallost** [comment]
hi, any news on this? The "request" library is causing audit issues, so a migration to axios is more than welcome

**Comment by droca** [comment]
Is this development abandoned?

**Pull request merged**
